import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Kurs Next.js | Nawigacja",
	description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="grid h-full flex-1 grid-cols-12">
			<div className="col-span-2 h-full bg-gray-300" />
			<div className="col-span-10 h-full">{children}</div>
		</div>
	);
}
